"""rename_event_datetime

Revision ID: 0d6fa483772d
Revises: 291a89b5a10c
Create Date: 2026-07-22 14:28:30.419914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6fa483772d'
down_revision: Union[str, Sequence[str], None] = '291a89b5a10c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages') as batch_op:
        batch_op.alter_column('session_id',
                              existing_type=sa.VARCHAR(),
                              nullable=False)
    with op.batch_alter_table('events') as batch_op:
        batch_op.alter_column('datetime', new_column_name='event_datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events') as batch_op:
        batch_op.alter_column('event_datetime', new_column_name='datetime')
    with op.batch_alter_table('chat_messages') as batch_op:
        batch_op.alter_column('session_id',
                              existing_type=sa.VARCHAR(),
                              nullable=True)
    # ### end Alembic commands ###
